### PR TITLE
add Chinese language

### PR DESCRIPTION
**Pull request by ittat**

### CODE REVIEW

**Comment by itsarjunsinh** [comment]
Hello @ittat, thanks for the Chinese translation. The generated files will be created during the build process For translation submissions the .arb files are required in version control. Could you add the .arb file instead?

I'm sorry for the late response.

**Comment by ittat** [comment]
Hi，I don't know much about Flutter. Do I just need to submit the arb file, or do I still need to supplement the arb file?

**Comment by itsarjunsinh** [comment]
You are correct, only the .arb file needs to be submitted.
Rather than opening a new PR undo the last commit and only push the .arb file.
Thanks again for contributing.

**Comment by ittat** [comment]
done, review again please

**Pull request merged**
